import { ThemeProvider } from "@mui/material";
import "./globals.css";
import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import { responsiveTheme } from "@/theme/theme";

const noto_sans = Noto_Sans({
  subsets: ["latin"],
  style: ["normal"],
  weight: ["200", "300", "400", "700", "800"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={noto_sans.className}>
        <ThemeProvider theme={responsiveTheme}>{children}</ThemeProvider>
      </body>
    </html>
  );
}
