import { ServersMenu } from '@/components/ServersMenu';
import { responsiveTheme } from '@/theme/theme';
import { Stack, ThemeProvider } from '@mui/material';
import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const noto_sans = Noto_Sans({
  subsets: ['latin'],
  style: ['normal'],
  weight: ['200', '300', '400', '700', '800'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <body className={noto_sans.className}>
        <ThemeProvider theme={responsiveTheme}>
          <Stack direction={'row'}>
            <ServersMenu />

            {children}
          </Stack>
        </ThemeProvider>
      </body>
    </html>
  );
}
